### PR TITLE
feat: Add Ledgity Yield adapter

### PR DESCRIPTION
**Pull request by LilaRest**
Hey there!
Here is the Ledgity Yield adapter.
Feel free to ping me if you have any questions.
Cheers!

### CODE REVIEW

**Comment by nitish-91** [comment]
@LilaRest Please check the changes we have made in readme and accommodate them. It will help us integrate the code better. Thank you for the help.

**Comment by LilaRest** [comment]
Hey @nitish-91, how does that look now?
There is a `getUserTVLByBlock.ts` file that exports the required function.

**Comment by nitish-91** [comment]
@LilaRest  please create a branch from the main branch of this repo, make your changes in that branch and create pull request to main. 
https://github.com/delta-hq/l2-lxp-liquidity-reward#notes

**Comment by nitish-91** [comment]
> @LilaRest please create a branch from the main branch of this repo, make your changes in that branch and create pull request to main. https://github.com/delta-hq/l2-lxp-liquidity-reward#notes

Please ignore this comment, we will figure this out internally

**Comment by 0xroll** [comment]
hi @LilaRest , how long will this take to do a full run to get user's data of a specific block? 

any possibility of getting rate limited here?

**Comment by LilaRest** [comment]
> hi @LilaRest , how long will this take to do a full run to get user's data of a specific block?
> 
> any possibility of getting rate limited here?

Hey @0xroll, it took only a few minutes last time I ran it, and I never experienced rate limits during my tests. If that were to happen, we could provide you with Infura endpoints.

**Comment by 0xroll** [comment]
@LilaRest okay, can you make some minor edits here

change the token address and user address to lowercase

since you are doing rpc calls the LUSDC rebase will all be accounted for .

once changes are made we can merge and test it  cc @nitish-91

**Comment by LilaRest** [comment]
Hey @0xroll, I applied the requested changes ✅

**Comment by 0xroll** [comment]
> Hey @0xroll, I applied the requested changes ✅

thanks!

lets try merge this @nitish-91

**Comment by 0xroll** [comment]
hi @LilaRest , we have a new workflow process that contains a checklist during pr submission. can you reopen a new pr and make sure everything in the checklist is done? it should be good to go after

**Pull request closed without merging**
