### PR TITLE
Feat: 3A DAO Adapter

### PR DESCRIPTION
**Pull request by bytes0xcr6**
Adapter for retrieving the Total Value Locked (TVL) and balance associated with each collateral deposited within our users' vaults.

### CODE REVIEW

**Comment by 0xroll** [comment]
hi @CristianRicharte6 , thanks for the PR.

i assume 3A DAO is a type of cdp protocol.

can i check for the stability pools, does it creates a LP token when user deposits?

if yes -> does the adapter tracks the token movement [ user a deposit -> transfer lp token to user b]

**Comment by CristianRicharte6** [comment]
Hi @0xroll ,

The stability pool does not create any LP tokens, it just gives A3A tokens (Our gobernance token) as reward for depositing EURO3.

- Stability pool: https://lineascan.build/address/0x51c3db485e3b21193636a83f05b3517f691cd68c#code

We are not using any subgraph for the adapter, as the TVL by vault/user has to be tracked individually from each vault due to the vaultFactory not emitting events about the collaterals deposited.  If we would want to use subgraph, we should be updating the subgraph every single time a new vault is created. That´s why we are using RPC calls for this. 

Let us know if we can help with anything else :) 

Thanks

**Comment by 0xroll** [comment]
@CristianRicharte6 i assume that is a public rpc? would this cause an issue when the protocol gets bigger? i believe its checking every single vault created from factory.

**Comment by CristianRicharte6** [comment]
@0xroll yest, its a public RPC. We already included helper contracts to reduce the amount of RPC calls to the minimum

**Comment by 0xroll** [comment]
@CristianRicharte6 got it, thanks.

we will likely need to monitor this, whether we will get rate limited from the public rpc.

lets try to merge this and see how it goes @nitish-91 @RamonReis

**Review by 0xroll — APPROVED** [review]

**Comment by nitish-91** [comment]
@CristianRicharte6 can you please implement the function as mentioned in readme. Basically, we would need a function with the same name as mentioned there.
https://github.com/delta-hq/l2-lxp-liquidity-reward#code-changes-expected

In case the rpc is too slow, we might ask you to host the api by yourself and expose from your backend.

**Comment by CristianRicharte6** [comment]
@nitish-91 the name of the main function has been updated to getUserTVLByBlock as mentioned in the readme. Let us know if you guys end up needing that API. 

Thanks :)

**Comment by 0xroll** [comment]
@bytes0xcr6 thanks!

one question, any possibility of getting rate limited from the rpc you are using? we see alot protocols using the same rpc

**Review by 0xroll — APPROVED** [review]

**Comment by 0xroll** [comment]
@bytes0xcr6 we prefer the current setup as it is more transparent. we can merge this and test it to see if we have any issues.

cc @nitish-91 lets merge

**Comment by nitish-91** [comment]
@bytes0xcr6 we made one change in readme. Can you please go through it and incorporate.

Basically, we need this function to be defined and called in index.ts . We call this function to get the data by providing the hourly_blocks.csv file. Till now our engg was doing it, now it is stable and protocols adding it will reduce manual intervention from our side

https://github.com/delta-hq/l2-lxp-liquidity-reward/blob/607b15fb653d8d0780046e27014344880fce109d/adapters/example/dex/src/index.ts#L134

**Comment by bytes0xcr6** [comment]
@nitish-91 @0xroll  I have just pushed the new changes to read from the hourly_blocks.csv. Please, let me know if more changes needs to be made.

**Comment by 0xroll** [comment]
hi @bytes0xcr6 , we have added a new checklist when submitting new PR. can you open a new pr and go through that checklist and ensure everything is covered? once its done we will be able to merge it

**Comment by bytes0xcr6** [comment]
@0xroll New PR Created https://github.com/delta-hq/l2-lxp-liquidity-reward/pull/149

**Pull request closed without merging**
