### PR TITLE
satori perps upgrade

### PR DESCRIPTION
**Pull request by miler012**
## Title: 

- [ ] Pattern for PR title "protocol_name : protocol_category : other comments". Example - "uniswap: dex : tvl by user"

## Checklist before requesting a review
1. **index.ts file**

     - [ ] **Contains function**

            ```export const getUserTVLByBlock = async (blocks: BlockData) => {
                const { blockNumber, blockTimestamp } = blocks
                    //    Retrieve data using block number and timestamp
                    // YOUR LOGIC HERE
                
                return csvRows

            };
            ``` 
    - [ ] **getUserTVLByBlock function takes input with this schema**
        
            ``` 
                interface BlockData {
                    blockNumber: number;
                    blockTimestamp: number;
                }
            ```
    - [ ] **getUserTVLByBlock function returns output in this schema**

                ```
                const csvRows: OutputDataSchemaRow[] = [];

                type OutputDataSchemaRow = {
                    block_number: number;  //block_number which was given as input
                    timestamp: number;     // block timestamp which was given an input, epoch format
                    user_address: string;   // wallet address, all lowercase
                    token_address: string;  // token address all lowercase
                    token_balance: bigint;  // token balance, raw amount. Please dont divide by decimals
                    token_symbol: string; //token symbol should be empty string if it is not available
                    usd_price: number; //assign 0 if not available
                };
                ```
    - [ ] **contains function**

            ```
                const readBlocksFromCSV = async (filePath: string): Promise<BlockData[]> => {
                const blocks: BlockData[] = [];

                await new Promise<void>((resolve, reject) => {
                    fs.createReadStream(filePath)
                    .pipe(csv()) // Specify the separator as '\t' for TSV files
                    .on('data', (row) => {
                        const blockNumber = parseInt(row.number, 10);
                        const blockTimestamp = parseInt(row.timestamp, 10);
                        if (!isNaN(blockNumber) && blockTimestamp) {
                        blocks.push({ blockNumber: blockNumber, blockTimestamp });
                        }
                    })
                    .on('end', () => {
                        resolve();
                    })
                    .on('error', (err) => {
                        reject(err);
                    });
                });

                return blocks;
                };

            ```
    - [ ] **has this code**
           
            ```
            readBlocksFromCSV('hourly_blocks.csv').then(async (blocks: any[]) => {
            console.log(blocks);
            const allCsvRows: any[] = []; 

            for (const block of blocks) {
                try {
                    const result = await getUserTVLByBlock(block);
                    allCsvRows.push(...result);
                } catch (error) {
                    console.error(`An error occurred for block ${block}:`, error);
                }
            }
            await new Promise((resolve, reject) => {
                const ws = fs.createWriteStream(`outputData.csv`, { flags: 'w' });
                write(allCsvRows, { headers: true })
                    .pipe(ws)
                    .on("finish", () => {
                    console.log(`CSV file has been written.`);
                    resolve;
                    });
            });

            }).catch((err) => {
            console.error('Error reading CSV file:', err);
            });
        ```
2. **Output data**
    - [ ] Data is returned for underlying tokens only. Not for special tokens (lp/veTokens etc)
    - [ ] Follows the exact sequence mentioned in OutputDataSchemaRow . This is needed as we want same column ordering in output csv
    - Value of each field is :
        - [ ] block_number *is same as input block number. This signifies TVL is as of this block_number.*
        - [ ] timestamp is same as input timestamp. This signifies TVL is as of this timestamp. It is in epoch format.
        - [ ] user_address is in lowercase
        - [ ] token_address is in lowercase
        - [ ] token_balance is in raw amount. Please dont divide by decimals.
        - [ ] token_symbol value if present, empty string if value is not available.
        - [ ] usd_price if value is available, 0 if value is not available.

### CODE REVIEW

**Comment by 0xroll** [comment]
not sure if you should have them all under satori/ , @nitish-91 to confirm.

the subgraph codes are private, based on the discussion with @miler012 , for perps tvl :

this is taking deposit - withdrawal , which doesnt factor in liquidations.
if users are being liquidated -> the adapter will still return the user having tvl because there are no withdrawals.

**Comment by nitish-91** [comment]
@miler012 please put everything under satori and make sure it is called from same index.ts function

**Comment by miler012** [comment]
under same package,need two outputdata or one with the  preps and  dex ?

**Comment by 0xroll** [comment]
> under same package,need two outputdata or one with the preps and dex ?

same csv just aggregate them together

**Comment by nitish-91** [comment]
@miler012 can you please check the boxes for things you have confirmed in the PR

**Comment by nitish-91** [comment]
@miler012 also, this seems to be having conflicts, please re-raise after rebasing with main

**Pull request closed without merging**
