### PR TITLE
Zypher Restaking : restaking : tvl by user

### PR DESCRIPTION
**Pull request by web3-penguin**
## Title: 

- [x] Pattern for PR title "protocol_name : protocol_category : other comments". Example - "uniswap: dex : tvl by user"

## Checklist before requesting a review
1. **index.ts file**

     - [x] **Contains function**

       ```ts
            export const getUserTVLByBlock = async (blocks: BlockData) => {
                const { blockNumber, blockTimestamp } = blocks
                    //    Retrieve data using block number and timestamp
                    // YOUR LOGIC HERE
                
                return csvRows

            };
       ``` 
    - [x] **getUserTVLByBlock function takes input with this schema**
        
       ```ts
                interface BlockData {
                    blockNumber: number;
                    blockTimestamp: number;
                }
       ``` 
    - [x] **getUserTVLByBlock function returns output in this schema**

       ```ts
                const csvRows: OutputDataSchemaRow[] = [];

                type OutputDataSchemaRow = {
                    block_number: number;  //block_number which was given as input
                    timestamp: number;     // block timestamp which was given an input, epoch format
                    user_address: string;   // wallet address, all lowercase
                    token_address: string;  // token address all lowercase
                    token_balance: bigint;  // token balance, raw amount. Please dont divide by decimals
                    token_symbol: string; //token symbol should be empty string if it is not available
                    usd_price: number; //assign 0 if not available
                };
       ``` 
    - [x] **contains function**

       ```ts
                const readBlocksFromCSV = async (filePath: string): Promise<BlockData[]> => {
                const blocks: BlockData[] = [];

                await new Promise<void>((resolve, reject) => {
                    fs.createReadStream(filePath)
                    .pipe(csv()) // Specify the separator as '\t' for TSV files
                    .on('data', (row) => {
                        const blockNumber = parseInt(row.number, 10);
                        const blockTimestamp = parseInt(row.timestamp, 10);
                        if (!isNaN(blockNumber) && blockTimestamp) {
                        blocks.push({ blockNumber: blockNumber, blockTimestamp });
                        }
                    })
                    .on('end', () => {
                        resolve();
                    })
                    .on('error', (err) => {
                        reject(err);
                    });
                });

                return blocks;
                };

       ``` 
    - [x] **has this code**
           
       ```ts
            readBlocksFromCSV('hourly_blocks.csv').then(async (blocks: any[]) => {
            console.log(blocks);
            const allCsvRows: any[] = []; 

            for (const block of blocks) {
                try {
                    const result = await getUserTVLByBlock(block);
                    allCsvRows.push(...result);
                } catch (error) {
                    console.error(`An error occurred for block ${block}:`, error);
                }
            }
            await new Promise((resolve, reject) => {
                const ws = fs.createWriteStream(`outputData.csv`, { flags: 'w' });
                write(allCsvRows, { headers: true })
                    .pipe(ws)
                    .on("finish", () => {
                    console.log(`CSV file has been written.`);
                    resolve;
                    });
            });

            }).catch((err) => {
                console.error('Error reading CSV file:', err);
            });
       ``` 
    - [x] **Your code is handling Pagination to make sure all data for a given block is returned**

2. **Output data**
    - [x] Created a folder test on the same level as src and put sample outputData.csv with 15-20 records generated by your code
    - [x] Data is returned for underlying tokens only. Not for special tokens (lp/veTokens etc)
    - [x] Follows the exact sequence mentioned in OutputDataSchemaRow . This is needed as we want same column ordering in output csv
    - Value of each field is :
        - [x] block_number *is same as input block number. This signifies TVL is as of this block_number.*
        - [x] timestamp is same as input timestamp. This signifies TVL is as of this timestamp. It is in epoch format.
        - [x] user_address is in lowercase
        - [x] token_address is in lowercase
        - [x] token_balance is in raw amount. Please dont divide by decimals.
        - [x] token_symbol value if present, empty string if value is not available.
        - [x] usd_price if value is available, 0 if value is not available.

### CODE REVIEW

**Comment by 0xroll** [comment]
hey @web3-penguin 
when will zypher likely to launch?

**Comment by web3-penguin** [comment]
We are still waiting for contract auditing, and not yet to have a exactly date to launch.

Do we need to return the empty mainnet TVL instead of testnet TVL?

**Comment by 0xroll** [comment]
@web3-penguin our pipeline only passes mainnet block number, so the current adapter wouldnt work.

would suggest to test it locally to see if the output is exactly , and make the changes once its live on mainnet

**Comment by web3-penguin** [comment]
Thank you for replying @0xroll, we had update the data source to the mainnet contract. 😃

**Comment by 0xroll** [comment]
@web3-penguin 

can you also share with me your gh repo for the subgraph?

are token transfers tracked here?

eg : user A mint -> transfer to user B

**Comment by web3-penguin** [comment]
Here is our subgraph repository: https://github.com/zypher-game/restaking-subgraph/blob/main/src/mappings.ts#L30-L66

We only log wrapped ETH deposits and withdrawals from external sources.
This does not include internally minted tokens for accounting or rewards purposes.

**Comment by 0xroll** [comment]
ah, there is no receipt token when users deposit?

**Comment by 0xroll** [comment]
@web3-penguin 

thanks, some final request before PR merge.

can you do a withdrawal tx as well (dont withdraw full balance)

can you also rename from `zypher_restaking` to just `zypher`

should we identify you as `Zypher Network` or `Zypher Games`?

**Comment by web3-penguin** [comment]
Got it, we're working on it. Please wait a moment. 😃 

Tasks:

- [x] Rename the folder (completed).
- [ ] Confirm project ownership
    - currently discussing with the PM.
- [ ] Withdraw a portion of the balance
    - currently working on a solution with the PM & Solidiity dev due to the 13-week lock-up period.

**Review by 0xroll — APPROVED** [review]

**Comment by 0xroll** [comment]
thanks @web3-penguin 

when are you guys going live?

**Pull request merged**
