### PR TITLE
Add interport adapter

### PR DESCRIPTION
**Pull request by bogdanuch**

### CODE REVIEW

**Comment by 0xroll** [comment]
hi @bogdanuch thanks for the PR.

iTokens have transfer events that  we should also be tracking of.

user A deposits -> transfer iToken to user B

**Comment by bogdanuch** [comment]
> hi @bogdanuch thanks for the PR.
> 
> iTokens have transfer events that we should also be tracking of.
> 
> user A deposits -> transfer iToken to user B

Do you want me to detect in possession of iToken at the end? Because the person who added the liquidity is the one who made deposit. 
I'm also not completely sure that Transfer is only used for deposit/withdrawal and transfer of tokens between users(I can check if it's what required).

**Comment by 0xroll** [comment]
> > hi @bogdanuch thanks for the PR.
> > iTokens have transfer events that we should also be tracking of.
> > user A deposits -> transfer iToken to user B
> 
> Do you want me to detect in possession of iToken at the end? Because the person who added the liquidity is the one who made deposit. I'm also not completely sure that Transfer is only used for deposit/withdrawal and transfer of tokens between users(I can check if it's what required).

so ideally we are looking at who owns the liquidity(TVL).
so yes, we should have the transfers event factored in as well to get the correct owner

**Comment by bogdanuch** [comment]
> > > hi @bogdanuch thanks for the PR.
> > > iTokens have transfer events that we should also be tracking of.
> > > user A deposits -> transfer iToken to user B
> > 
> > 
> > Do you want me to detect in possession of iToken at the end? Because the person who added the liquidity is the one who made deposit. I'm also not completely sure that Transfer is only used for deposit/withdrawal and transfer of tokens between users(I can check if it's what required).
> 
> so ideally we are looking at who owns the liquidity(TVL). so yes, we should have the transfers event factored in as well to get the correct owner

Is it better right now?

**Comment by 0xroll** [comment]
thanks, please remember to submit new PRs when new token pools are integrated in your protocol.

lets merge this @nitish-91

**Review by 0xroll — APPROVED** [review]

**Pull request merged**
