### PR TITLE
feat: add mendi adapter

### PR DESCRIPTION
**Pull request by gathonwar**
fix: zero values and math rounding

### CODE REVIEW

**Comment by 0xroll** [comment]
hi @gathonwar 

some questions on this PR :

1) is this returning the net balance? net asset balance = supplied - borrowed
2) this doesnt seem to factor in interests gained/accrued from supplying and borrowing

**Comment by nitish-91** [comment]
@gathonwar can you please implement the function as mentioned in the readme. 
https://github.com/delta-hq/l2-lxp-liquidity-reward/tree/main?tab=readme-ov-file#code-changes-expected

Also please reply to @0xroll 's questions

**Comment by gathonwar** [comment]
hi @0xroll,

1. yes, these are net balances
2. interest are accumulated in supply side because we are using tokens and exchange rate to calculate supplied amount. they were not included in borrow side, the second commit is getting borrow balance at block number (interests are included).

**Comment by 0xroll** [comment]
@RamonReis @nitish-91 lets try to have this merged

**Review by 0xroll — APPROVED** [review]

**Pull request merged**
