### PR TITLE
add adapter for CSV data of the Deri Protocol

### PR DESCRIPTION
**Pull request by deri-tianyang**
Please note that the token address 0x0000000000000000000000000000000000000001 in the outputData.csv file is the ETH address.

### CODE REVIEW

**Comment by nitish-91** [comment]
Please check the changes we have made in readme and accommodate them. It will help us integrate the code better. Thank you for the help.

**Comment by deri-tianyang** [comment]
@nitish-91 Thanks, I have modified it. Could you please check it again?

**Comment by nitish-91** [comment]
> @deri-tianyang please create a branch from the main branch of this repo, make your changes in that branch and create pull request to main. https://github.com/delta-hq/l2-lxp-liquidity-reward#notes

Please ignore this comment, we will figure this out internally

**Comment by 0xroll** [comment]
hi @deri-tianyang thanks for the PR.

was looking at the dapp, have some questions :

1) does the tvl provided by users represents the liquidity for other traders to trade on? if yes, are we tracking the pnl changes that can affect the user's tvl?

2) are there LP tokens provided when user provide liquidity? if yes, are we tracking the ownership transfer [user A provide LP -> transfer token to user B

feel free to dm me on telegram if its easier , @jh_onchain

**Comment by deri-tianyang** [comment]
> hi @deri-tianyang thanks for the PR.
> 
> was looking at the dapp, have some questions :
> 
> 1. does the tvl provided by users represents the liquidity for other traders to trade on? if yes, are we tracking the pnl changes that can affect the user's tvl?
> 2. are there LP tokens provided when user provide liquidity? if yes, are we tracking the ownership transfer [user A provide LP -> transfer token to user B
> 
> feel free to dm me on telegram if its easier , @jh_onchain

hi @0xroll thank you for your questions, here are the answers:
1. Yes, we track the pnl changes that can affect the user's tvl.
2. Yes, we check the transfer events of the LP token, and the final owner (user B in your question) of the LP token is the tvl owner.

**Comment by 0xroll** [comment]
@deri-tianyang sounds good, can you provide me the github repo link for the subgraphs?

should be good to merge @nitish-91 @RamonReis

**Comment by 0xroll** [comment]
hi @deri-tianyang checking the data from the adapter atm and have some questions to ask.

getting different balances from data vs debank, also it seems like not everything is indexed on debank too.

lets discuss this, can you dm me on telegram @jh_onchain

**Pull request merged**
