### PR TITLE
add izumiswap adapter

### PR DESCRIPTION
**Pull request by LpcAries**
add izumiswap lp adapter based on subgraph on Linea

### CODE REVIEW

**Comment by nitish-91** [comment]
@LpcAries  please create a branch from the main branch of this repo, make your changes in that branch and create pull request to main. 
https://github.com/delta-hq/l2-lxp-liquidity-reward#notes

**Comment by LpcAries** [comment]
> @LpcAries please create a branch from the main branch of this repo, make your changes in that branch and create pull request to main. https://github.com/delta-hq/l2-lxp-liquidity-reward#notes

It seems that I do not have access to commit a branch to the main repo directly.

**Comment by nitish-91** [comment]
> > @LpcAries please create a branch from the main branch of this repo, make your changes in that branch and create pull request to main. https://github.com/delta-hq/l2-lxp-liquidity-reward#notes
> 
> It seems that I do not have access to commit a branch to the main repo directly.

Please ignore this comment, we will figure this out internally

**Comment by nitish-91** [comment]
> @LpcAries please create a branch from the main branch of this repo, make your changes in that branch and create pull request to main. https://github.com/delta-hq/l2-lxp-liquidity-reward#notes

Please ignore this comment, we will figure this out internally

**Comment by 0xroll** [comment]
@LpcAries thanks for the update .

one last thing, does this cover transfers of asset between users?

if user A mints -> transfer to user B . is this covered here?

**Comment by LpcAries** [comment]
> @LpcAries thanks for the update .
> 
> one last thing, does this cover transfers of asset between users?
> 
> if user A mints -> transfer to user B . is this covered here?

The subgraph is listening `Transfer` event to confirm getting the correct user on the block you want to check.

**Review by 0xroll — APPROVED** [review]

**Comment by 0xroll** [comment]
@LpcAries sounds good, thanks for the prompt responses

@RamonReis lets merge this and check whether the output looks good

**Comment by 0xroll** [comment]
@LpcAries hey, can we have the raw amount instead? currently its providing the token real amount

**Comment by LpcAries** [comment]
> @LpcAries hey, can we have the raw amount instead? currently its providing the token real amount

committed pr, plz check: https://github.com/delta-hq/l2-lxp-liquidity-reward/pull/65

**Pull request merged**
