### PR TITLE
Add Clip Finance Adapter

### PR DESCRIPTION
**Pull request by VitaliyShulik**

### CODE REVIEW

**Comment by nitish-91** [comment]
@VitaliyShulik  please create a branch from the main branch of this repo, make your changes in that branch and create pull request to main. 
https://github.com/delta-hq/l2-lxp-liquidity-reward#notes

**Comment by VitaliyShulik** [comment]
> @VitaliyShulik please create a branch from the main branch of this repo, make your changes in that branch and create pull request to main. https://github.com/delta-hq/l2-lxp-liquidity-reward#notes

@nitish-91  I do not have access to commit a branch to the main repo directly. Can you provide it to my GitHub account?

**Comment by nitish-91** [comment]
> @VitaliyShulik please create a branch from the main branch of this repo, make your changes in that branch and create pull request to main. https://github.com/delta-hq/l2-lxp-liquidity-reward#notes

Please ignore this comment, we will figure this out internally

**Comment by nitish-91** [comment]
@VitaliyShulik can you please look at readme and expose the relevant function which uses the expected input and produces expected output.

**Comment by mvp1983** [comment]
> @VitaliyShulik can you please look at readme and expose the relevant function which uses the expected input and produces expected output.

@nitish-91 I've created a new PR (https://github.com/delta-hq/l2-lxp-liquidity-reward/pull/83) which addresses issues which you mentioned.

**Comment by mvp1983** [comment]
> > @VitaliyShulik can you please look at readme and expose the relevant function which uses the expected input and produces expected output.
> 
> @nitish-91 I've created a new PR (#83) which addresses issues which you mentioned.
> 
> This PR can be rejected.

#92

**Pull request closed without merging**
